server:
  port: 8080

spring:
  application:
    name: ms-gateway

  cloud:
    gateway:
      routes:
        # Auth Service Route - fərqli prefix
        - id: auth-service
          uri: http://ms-auth:8081
          predicates:
            - Path=/authentication/**, /authentication/v3/api-docs/**
          filters:
            - StripPrefix=1

        # Event Service Route - fərqli prefix
        - id: event-service
          uri: http://ms-event:8082
          predicates:
            - Path=/events/**, /events/v3/api-docs/**
          filters:
            - StripPrefix=1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: /authentication/v3/api-docs
        name: MS Auth
      - url: /events/v3/api-docs
        name: MS Event



secretKey: U2ltcGx5IGVudGVyIHlvdXIgZGF0YSB0aGVuIHB1c2ggdGhlIGVuY29kZSBidXR0b24uU2ltcGx5IGVudGVyIHlvdXIgZGF0YSB0aGVuIHB1c2ggdGhlIGVuY29kZSBidXR0b24uU2ltcGx5IGVudGVyIHlvdXIgZGF0YSB0aGVuIHB1c2ggdGhlIGVuY29kZSBidXR0b24uCg==
