server:
  port: 8080

spring:
  application:
    name: ms-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://ms-auth:8081
          predicates:
            - Path=/auth/**, /api/users/**

        - id: event-service
          uri: http://ms-event:8082
          predicates:
            - Path=/event/**, /api/events/**, /api/sessions/**, /api/speakers/**


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: /auth/v3/api-docs
        name: MS Auth
      - url: /event/v3/api-docs
        name: MS Event


secretKey: U2ltcGx5IGVudGVyIHlvdXIgZGF0YSB0aGVuIHB1c2ggdGhlIGVuY29kZSBidXR0b24uU2ltcGx5IGVudGVyIHlvdXIgZGF0YSB0aGVuIHB1c2ggdGhlIGVuY29kZSBidXR0b24uU2ltcGx5IGVudGVyIHlvdXIgZGF0YSB0aGVuIHB1c2ggdGhlIGVuY29kZSBidXR0b24uCg==
