server:
  port: 8080

spring:
  application:
    name: ms-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://ms-auth:8081
          predicates:
            - Path=/auth/**, /api/users/**, /auth/v3/api-docs

        - id: event-service
          uri: http://ms-event:8082
          predicates:
            - Path=/api/events/**, /api/sessions/**, /api/speakers/**, /event/v3/api-docs

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: http://localhost:8080/auth/v3/api-docs
        name: MS Auth
      - url: http://localhost:8080/event/v3/api-docs
        name: MS Event
