server:
  port: 8080

spring:
  application:
    name: ms-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**, /api/users/**
        - id: event-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/events/**, /api/sessions/**, /api/speakers/**

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: http://localhost:8081/v3/api-docs
        name: MS Auth
      - url: http://localhost:8082/v3/api-docs
        name: MS Event

secretKey: U2ltcGx5IGVudGVyIHlvdXIgZGF0YSB0aGVuIHB1c2ggdGhlIGVuY29kZSBidXR0b24uU2ltcGx5IGVudGVyIHlvdXIgZGF0YSB0aGVuIHB1c2ggdGhlIGVuY29kZSBidXR0b24uU2ltcGx5IGVudGVyIHlvdXIgZGF0YSB0aGVuIHB1c2ggdGhlIGVuY29kZSBidXR0b24uCg==
