apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-gateway-deployment
  labels:
    app: ms-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-gateway
  template:
    metadata:
      labels:
        app: ms-gateway
    spec:
      containers:
        - name: ms-gateway
          image: docker.io/mmmdliayxan321/ms-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080