name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build with Spotless Auto-Fix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      - name: Apply Spotless Fixes
        run: ./gradlew spotlessApply

      - name: Spotless Check
        run: ./gradlew spotlessCheck

      - name: Build project (skip tests)
        run: ./gradlew clean build -x test --no-daemon

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19

      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test --no-daemon

  check-imports:
    name: Check Unused Imports
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19

      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      - name: Check unused imports
        run: ./gradlew spotlessCheck || { echo "Unused imports found"; exit 1; }
